window.ScrollReveal = require('~/node_modules/scrollreveal/src/scrollreveal.js')
window.Velocity = require('~/node_modules/velocity-animate/velocity.js')
window.axios = require('~/node_modules/axios/dist/axios.min.js')
//window.hljs = require('../node_modules/highlight.js/lib/highlight.js')
//window.fetch = require('~/node_modules/whatwg-fetch/fetch.js')